name: Cypress JIRA CLOUD API Test Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Build Docker Image
      - name: Build Docker Image
        run: docker build --no-cache -t cypress-jira-api -f docker/Dockerfile .

      # Step 3: Run Cypress tests in Docker
      - name: Run Cypress tests in Docker
        run: |
          docker run -v $(pwd)/mochawesome-report:/app/cypress/mochawesome-report cypress-jira-api:latest

      # Step 4: Upload Mochawesome reports
      - name: Upload Mochawesome reports
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome-report
          path: mochawesome-report/*.html
